server:
  port: 8080

spring:
  application:
    #应用的名称，可选
    name: railway_take_out
  shardingsphere:
    datasource:
      names:
        master,slave
      # 主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.108.129:3306/railway?characterEncoding=utf-8
        username: root
        password: 111111
      # 从数据源
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.108.130:3306/railway?characterEncoding=utf-8
        username: root
        password: 111111
    masterslave:
      # 读写分离配置
      load-balance-algorithm-type: round_robin #轮询
      # 最终的数据源名称
      name: dataSource
      # 主库数据源名称
      master-data-source-name: master
      # 从库数据源名称列表，多个逗号分隔
      slave-data-source-names: slave
    props:
      sql:
        show: true #开启SQL显示，默认false
  main:
    #允许bean定义覆盖配置项（不然和默认Durid数据源写入冲突）
    allow-bean-definition-overriding: true
  redis:
    # redis 的 IP 地址
    host: hadoop128
    # redis的端口
    port: 6379
    # 使用redis的数据库0
    database: 0
  # spring cache的使用
  cache:
    # 指定使用的缓存类型
    type: redis
    #设置过期时间
    redis:
      time-to-live: 1800000
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path: railway_take_out/src/main/resources/image/

